version: '3.11'

services:
  regression:
    image: pytest:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/yadro_test
    command: /bin/sh -c "ls -la && pytest -sv --alluredir=allure-results && /usr/bin/allure generate --clean"
    working_dir: /yadro_test